name: CI / Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (ci if lockfile exists, else install)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if [ -f ./package-lock.json ] || [ -f ./npm-shrinkwrap.json ] || [ -f ./yarn.lock ]; then
            echo "Lockfile found — running npm ci"
            npm ci
          else
            echo "No lockfile — running npm install"
            npm install
          fi

      - name: Build (only if npm run build exists)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if grep -q '"build"' package.json; then
            npm run build
          else
            echo "No build script — skipping build"
          fi

      # Optional: run tests, lint, etc.

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .          # deploy from repository root

